spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: order-service

application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    payment-url: http://localhost:8222/api/v1/payments
    product-url: http://localhost:8222/api/v1/products




server:
  servlet:
    context-path: /api/v1/
