spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: http://localhost:8222
          predicates:
            - Path=/api/v1/auth/**
        - id: customer-service
          uri: http://localhost:8222
          predicates:
            - Path=/api/v1/customers/**
        - id: order-service
          uri: http://localhost:8222
          predicates:
            - Path=/api/v1/orders/**

logging:
  level:
    org.springframework.security: DEBUG
    com.linh.gateway.security: DEBUG
