spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: auth-service
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000 # a day
        refresh-token:
          expiration: 604800000 # 7 days
    mailing:
      frontend: http://localhost:4200/activate-account

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
server:
  servlet:
    context-path: /api/v1/
