spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

payos:
  client-id:
  api-key:
  checksum-key:
  base-url: https://api-sandbox.payos.vn
server:
  port: 8083
  servlet:
    context-path: /api/v1/
