spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloudflare:
    domain: shopfinity.live
    api:
      token: LVzJoGjFZ8CdWncIqL373Oag9Oa95f1O1rIl4EO2
    zone:
      id: d7104e974a8d96ebbc2e9bba1fff0e11
  application:
    name: customer-service
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000 # a day
        refresh-token:
          expiration: 604800000 # 7 days
    mailing:
      frontend: http://localhost:4200/activate-account

application:
  config:
    auth-url: http://localhost:8060/api/v1/auth
server:
  servlet:
    context-path: /api/v1/